#!/bin/bash
case "$1" in
	firefox)
		cp -f manifests/firefox.json src/manifest.json
		;;
	chrome)
		cp -f manifests/chrome.json src/manifest.json
		;;
	clean)
		rm -rf packages
		rm -f src/manifest.json
		exit 0
		;;
	*)
		echo "No build target."
		exit 1
		;;
esac

VERSION=$(cat VERSION)
sed -i "s/{VERSION}/$VERSION/g" src/manifest.json
PACKAGE="ytsb-$1-v$VERSION.zip"

mkdir -p packages
zip -rqj "packages/$PACKAGE" src/*
zip -rqg "packages/$PACKAGE" icons
rm -f src/manifest.json
echo "$PACKAGE"
