#!/bin/bash
case "$1" in
	firefox)
		cp -v manifests/firefox_manifest.json manifest.json
		;;
	chrome)
		cp -v manifests/chrome_manifest.json manifest.json
		;;
	clean)
		rm -rf web-ext-artifacts
		rm -f manifest.json
		exit 0
		;;
	*)
		echo "No build target."
		exit 1
		;;
esac

web-ext build \
	--overwrite-dest \
	--ignore-files \
		"build" "LICENSE" "README.md" "manifests" "icon-attributes.html"
