#!/bin/bash
case "$1" in
	firefox)
		cp -f manifests/firefox_manifest.json manifest.json
		;;
	chrome)
		cp -f manifests/chrome_manifest.json manifest.json
		;;
	clean)
		rm -rf packages
		rm -f manifest.json
		exit 0
		;;
	*)
		echo "No build target."
		exit 1
		;;
esac

VERSION=$(jq -r '.version' manifest.json)
PACKAGE="ytsb-$1-v$VERSION.zip"

mkdir -p packages

zip -rq "packages/$PACKAGE" . \
	-x "packages/*" "build" "LICENSE" "README.md" "manifests/*" "icon-attributes.html"

[[ $? = 0 ]] && echo "$PACKAGE"
